### ISSUE TITLE
Unable to find ServletContextHandler when including VStepper in WAR

### ISSUE THREAD

**Issue by markhm** [mLottmann/VStepper#3]
Hi Matthias,

When I include VStepper in my WAR, my application will no longer start correctly in Tomcat. It gives the following error:

```
Caused by: java.lang.IllegalStateException: Unable to find ServletContextHandler for provided ServletContext
at org.eclipse.jetty.websocket.server.NativeWebSocketServletContainerInitializer.onStartup(NativeWebSocketServletContainerInitializer.java:120)
at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5140)
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
... 43 more
```

I build my application as WAR to easily deploy it to Heroku. Without VStepper, my application works as expected. To isolate the issue, have varied also the Vaadin version, the Spring Boot version and the Tomcat version, but this did not have any effect and gave me the same error with VStepper and no error without VStepper.

I tried to see if I could find anything that could explain this behaviour in the `VStepper-1.0.7.jar`, e.g. an extra `server.xml` file, but I did not find anything strange. 

I have no problem when I start my application locally via main `Application extends SpringBootServletInitializer`. 

I am using:
Vaadin 14.1.25
Spring Boot 2.2.6.RELEASE
Tomcat 9.0.33

Your thoughts are highly appreciated. 🙏🏻

**Comment by markhm** [comment]
I have been able to change my Heroku deployment method from WAR to JAR, which caused this issue to disappear. So closing this one.
